name: Publish events-db-migration to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/darc-software/events-db-migration

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Build & Push (latest, main, sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:main
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy-migration:
    name: Deploy migration over SSH
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Run helm upgrade on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.K3S_SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          envs: GITHUB_SHA
          script: |
            set -euo pipefail
            export KUBECONFIG="$HOME/.kube/config"
            
            kubectl cluster-info >/dev/null
            
            # Redeploy Job with the *fresh* image from this commit
            kubectl -n data delete job/events-db-migration --ignore-not-found
            
            helm upgrade --install events-db-migration ./charts/events-db-migration \
              -n data \
              -f releases/data/events-db-migration/values.yaml \
              --set image.tag=${GITHUB_SHA}
            
            # Wait for the known job name = release name
            kubectl -n data wait --for=condition=complete --timeout=15m job/events-db-migration
            
            # Show logs from the Job pods
            kubectl -n data logs -l job-name=events-db-migration --all-containers --tail=-1