name: Publish events-db-migration to GHCR

on:
  push:
    branches: [ main ]
    # (optional) only rebuild when migrator changes
    # paths:
    #   - "events-db-migrate/**"
    #   - ".github/workflows/docker-publish.yml"

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/darc-software/events-db-migration

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your Dockerfile lives in a subdir (monorepo), set context/file accordingly:
      #   context: ./events-db-migrate
      #   file: ./events-db-migrate/Dockerfile
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest, main, sha)
        uses: docker/build-push-action@v6
        with:
          context: .                      # change to ./events-db-migrate if needed
          file: ./Dockerfile              # change to ./events-db-migrate/Dockerfile if needed
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:main
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false               # smaller manifest; optional